### ISSUE TITLE
[item #05] Interface, Supplier?

### ISSUE THREAD

**Issue by daeho-ro** [now-study/study-effective-java#10]
책에서 Supplier를 소개하면서 다음과 같은 코드를 보여주고 있습니다.
```
Mosaic create(Supplier<? extends Tile> tileFactory) {
    // do something
}
```

아마도... Tile은 추상 클래스이거나 인터페이스일 것으로 보이고 이를 상속받은 다양한 Tile 클래스가 존재하여 여러 클래스에 대한 인풋을 받고 Mosaic을 만들어주는 메서드로 보입니다. 그런데, 굳이 Supplier를 사용해야 하는 이유가 있을까요? 그냥 인터페이스나 부모 클래스 자체를 넘겨도 상속받은 자식 클래스들이 모두 인식되지 않나요?

Supplier를 사용하는 이유가 잘 와닿지가 않네요. Supplier는 무조건 새로운 인스턴스를 제공하는 정도의 차이를 가지고 쓰는 것인지...

**Comment by hailey21** [comment]
Supplier는 인자 없이 T 타입을 객체를 반환하는 `함수형 인터페이스`입니다.
Supplier를 왜 사용하는가에 대한 내용은 결국 함숭형 인터페이스를 왜 사용하는 것인가에 대한 질문과 동일하다고 볼 수 있습니다.

사용법은 알고 계실테지만, 결국 그 의미는 함수를 변수화 할 수 있고, 변수로 다룰 경우 직접 계산하지 않아도 된다는 장점이 있습니다.
즉 `Lazy Evaluation`, 입력값 없이 결과를 주는 편리한 친구지만 내가 원하는 걸 미리 준비하지 않아도 되는 게으른 공급자라고 생각하시면 될 것 같은데요.

샘플 코드를 첨부합니다.
여기서는 단순화를 위해 String 객체를 생성하도록 코드를 작성했습니다.

```java
package com.soojung.effectivejava.supplier;

import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;

public class NumberValidator {

    public static void main(String[] args) {

        long start = System.currentTimeMillis();

        isPositiveOrZero(1, veryExpensiveProcessing());
        isPositiveOrZero(-1, veryExpensiveProcessing());
        isPositiveOrZero(-2, veryExpensiveProcessing());

        System.out.println("no supplier time :  " + (System.currentTimeMillis() - start) / 1000 + "s");

        long startWithSupplier = System.currentTimeMillis();

        isPositiveOrZeroWithSupplier(1, () -> veryExpensiveProcessing());
        isPositiveOrZeroWithSupplier(-1, () -> veryExpensiveProcessing());
        isPositiveOrZeroWithSupplier(-2, () -> veryExpensiveProcessing());

        System.out.println("supplier time :  " + (System.currentTimeMillis() - startWithSupplier) / 1000 + "s");
    }

    private static String veryExpensiveProcessing() {
        try {
            TimeUnit.SECONDS.sleep(3);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        return "good";
    }

    private static void isPositiveOrZero(int number, String value) {
        if (number >= 0) {
            System.out.println("This value is positive or zero :: " + value);
        } else {
            System.out.println("Invalid");
        }
    }

    private static void isPositiveOrZeroWithSupplier(int number, Supplier<String> valueSupplier) {
        if (number >= 0) {
            System.out.println("This value is positive or zero :: " + valueSupplier.get());
        } else {
            System.out.println("Invalid");
        }
    }
}
```
제가 실행한 결과입니다.

> This value is positive or zero :: good
Invalid
Invalid
no supplier time :  9s
This value is positive or zero :: good
Invalid
Invalid
supplier time :  3s


NumberValidator 클래스의 isPositiveOrZero 메서드는 number가 0과 같거나 큰지 판단하여 결과값을 출력해주는 함수입니다.
여기서 출력해줘야 할 결과값은 아주 큰 비용이 들어가는 고비용 함수라고 가정합니다. (코드에서는 3초의 sleep 시간을 주는 것으로 표현했습니다.)
이 출력값은 0과 같거나 큰 경우에만 필요하지만 isPositiveOrZero 함수를 사용하여 직접 계산을 할 경우에는 순차적으로 모든 코드를 실행하기 때문에 실제로 값이 필요하지 않은 -1, -2 인 상황에서도 고비용의 함수를 호출합니다. 따라서 실제로는 9초의 시간이 걸린다고 표시됩니다.

그러나 Supplier를 사용하는 isPositiveOrZeroWithSupplier 함수를 사용하면 조건에 만족하는 경우에만 고비용 함수가 실행되도록 실행을 지연시킬 수 있는 이점이 있어 결과적으로는 수행 시간이 단축됩니다.

이런 특수한 상황에서 잘 활용해보시면 될것 같습니다.
