### ISSUE TITLE
[item #03] 싱글턴의 인터페이스 적용 예시

### ISSUE THREAD

**Issue by daeho-ro** [now-study/study-effective-java#12]
본문 23페이지:
> 클래스를 싱글턴으로 만들면 이를 사용하는 클라이언트를 테스트하기가 어려워질 수 있다. 타입을 인터페이스로 정의한 다음 그 인터페이스를 구현해서 만든 싱글턴이 아니라면 싱글턴 인스턴스를 가짜(mock) 구현으로 대체할 수 없기 때문이다.

그렇다면 싱글턴을 테스트하기 위해서는 인터페이스를 사용해야 한다는 뜻인데, 책에서는 딱히 예시를 들어주지 않고 있습니다. 어떻게 만들어야 할까요?

대강 생각나는 방법은...
```java
interface class Person {
    private static final INSTANCE;
    public static Person getInstance();
    public void leaveTheBuilding();
}

public class Elvis implements Person {...}
public class PersonMock implements Person {...}

class ElvisTest {
    private Person test = new PersonMock();
    @Test
    public void test() {...}
}
```
그렇지만, 이렇게 한다고 하더라도 이미 생성된 인스턴스를 테스트 용도의 Mock 인스턴스로 바꿀수가 없을 것 같은데... 인터페이스를 이용해서 테스트가 가능하게 하는 방법이 대체 어떻게 구현되는 걸까요? 혹은 이 방법이 아니더라도, 싱글턴을 테스트할 수 있는 방법이 궁금합니다.

**Comment by miyeon396** [comment]
일단, 싱글톤 자체를 테스트하는 것이 아니고,
테스트하려는 클래스가 싱글톤에 의존하는 경우의 테스트를 진행하는 것에 대한 이슈인데,
이를 해결하여(좋은방법은 아니지만) 테스트를 진행할 수 있는 몇 가지 방법입니다.

1. 인터페이스 상속해서 구현한 후 해당 인터페이스를 사용해 클래스에 싱글톤을 주입해라 
https://stackoverflow.com/questions/8256989/singleton-and-unit-testing
https://www.anycodings.com/1questions/796464/mocking-a-singleton-class
https://stackoverflow.com/questions/25273210/why-is-a-singleton-class-hard-to-test

    - 테스트를 하려면 목객체를 주입해야하는데 싱글톤의 경우 실제 객체 + 스태틱 영역 + 생성자 프라이빗이라 주입이 어렵다.
    - 모의 객체 만들어서(=인터페이스 구현하여) 사용 시 객체의 라이프사이클 관리를 테스트하는 시점에 제어할 수 있어서 해당 방법은 제시하는 것 같음.
    
```java
interface Singleton {
    private static final myInstance;
    public static Singleton getInstance() { return myInstance; }
    public static void setInstance(Singleton newInstance) { myInstance = newInstance; }
    // public method declarations
}

// Used in production
class RealSingleton implements Singleton {
    // public methods
}

// Used in unit tests
class FakeSingleton implements Singleton {
    // public methods
}

class ClientTest {
    private Singleton testSingleton = new FakeSingleton();
    @Test
    public void test() {
        Singleton.setSingleton(testSingleton);
        client.doSomething();
        // ...
    }
}
```
2. PowerMock을 사용하라

3. 리플렉션 사용
https://tony950620.tistory.com/87

5. sintleton 사용하지마라
-> 모든 테스트간 동일한 객체가 공유되므로 하지마라
