### ISSUE TITLE
[item #03] 싱글턴의 목적으로 열거타입을 사용하는 이유

### ISSUE THREAD

**Issue by hyojae93** [now-study/study-effective-java#13]
책 본문에서 복잡한 직렬화 상황이나 리플렉션 공격에서도 제2의 인스턴스가 생기는 일을 막아준다고 나와 있지만
열거타입은 보통 원소가 여러개가 선언된 모습을 보았는데
싱글턴을 만들기 위해 하나만 정의하게 된다면 열거타입을 사용하는 이유가 뭘까요?

**Comment by miyeon396** [comment]
enum 인스턴스 자체가 싱글턴이고 이런 특징을 이용해서 싱글턴을 구현하는 것이지 그렇다고 enum 내부의 원소가 한개일 필요는 없다고 이해를 했습니다.

우선, `열거 타입을 싱글톤으로 사용하라`는 이유에 대해서 먼저 설명을 하겠습니다.

**enum 의 특징**
- private 생성자로 인스턴스 생성을 제어하며, 상수만 갖는 특별한 클래스로 싱글톤의 성질을 갖고 있다.     
- 싱글톤을 간단하게 구현할 때 사용되곤 한다.

**enum을 사용 싱글톤의 장점**
1. 간단함
    - enum 인스턴스의 생성은 기본적으로 `thread-safe` -> 쓰레드 관련 코드를 고민할 필요가 없어 코드가 간단
    (하지만 enum 내의 다른 메서드들에 대해서는 프로그래머가 thread-safe를 책임져야 한다.)
2. Serializable을 스스로 해결한다.
    - 일반적인 싱글톤에서는 직렬화 시 싱글톤이 싱글톤이 아니게 되는 문제가 발생한다. 
    (직렬화 시 readObject()를 구현해야하는데, readObject()는 매번 새로운 인스턴스를 리턴하기 때문)  
    - Enum Singleton에서는 직렬화 이슈 처리 불필요. -> `JVM이 enum의 Serialization을 보장`
3. Reflection 공격에 안전
    - 싱글톤 생성 시 생성자가 private이라도 Reflection을 이용하면 외부에서 객체 생성이 가능하지만 Enum의 경우에는 이런 `Reflection을 통한 공격에도 안전`하다.
    - enum 클래스의 생성자는 내부에서만 액세스가 가능

-> 위와 같은 enum을 이용한 싱글톤의 장점들과 동일한 이유로 책에서는 완벽한 싱글톤을 위해 Enum을 통한 구현을 권장을 하고는 있음

_하지만, enum을 통한 싱글톤이 꼭 좋다고는 말할 수 없음._ 

**enum을 싱글톤으로 사용하지 않아야할 이유** 
1. enum의 본래의 목적과 어긋남.
    - 열거형은 기본적으로 `상수`에 해당하는 개념을 표기하기 위한 언어의 개념이고, 객체지향에서 싱글톤 인스턴스를 사용하는 용도와 전혀 관계가 없음.
    - 싱글톤의 단점으로 제시된 내용중 어느것도 근본적 개념의 차이를 부시하고 enum을 오용해야할 만큼 심각한 사안은 아님
2. 실제 업무에서 싱글톤을 직접 구현하기보다는 `스프링 컨테이너를 이용한 싱글톤`을 주로 사용
3. 실제로 enum을 싱글톤으로 사용하는 사례가 거의 없음(솔직히 본적이 없음) -> 혼란 가중

원리적인 측면에서 보았을 땐, 싱글톤 구현의 모든 문제들을 해결하는 enum은 완벽한 싱글톤으로 이를 사용하기에 알맞아 보이나, 
실제 업무에서 enum을 싱글톤 구현으로 사용하는데는 적합해 보이지는 않습니다.
