### ISSUE TITLE
[item #03] 자바와 스프링에서의 싱글톤 개념이 조금 다른 것 같은데 설명 부탁드립니다.

### ISSUE THREAD

**Issue by hailey21** [now-study/study-effective-java#14]
싱글톤의 개념은 동일하지만 자바의 싱글톤 패턴은 안티패턴으로 불리기도 하면서 스프링의 싱글톤과는 그 내용이 조금 다른 것 같습니다.
왜 안티패턴으로 불리는지 내용과 차이점을 소개해주시면 감사하겠습니다.

**Comment by miyeon396** [comment]
Java의 싱글톤과 스프링의 싱글톤은 `어떤 클래스의 객체가 어플리케이션 내에서 하나의 인스턴스만 존재하고 여러 클라이언트에서 공유한다`는 공통점이 있지만 일부 차이가 있습니다.

**Java와 Spring의 싱글톤 차이**
||Java|Spring|
|---|---|---|
|단위|ClassLoader당 특정 클래스의 하나의 인스턴스를 보장|Spring Container당 하나의 빈, 하나의 인스턴스 보장 |
|Scope|코드 전체|스프링 컨테이너 내부|
|Thread-Safety|Logic에 따라 보장 못함|자동 보장 -> Bean의 관리 주체인 스프링 컨테이너는 항상 단인 공유 인스턴스를 리턴시키므로|
|특징| - 해당 클래스의 인스턴스는 하나만 만들 수 있다.<br /> -외부 클래스로부터 인스턴스화 되는 것을 막기위해 생성자는 private로 선언 <br/> - 인스턴스화된 클래스를 static 변수로 선언  | - 컨테이너 안에서 특정 클래스에 대해서 Bean이 정의되면 스프링 컨테이너는 그 클래스에 대해서 하나의 인스턴스를 만듦. <br/> - Bean 호출마다 스프링은 생성된 공유 인스턴스를 리턴. |

**Java 싱글톤 non-Thread-Safety 예제**
```
public class Singleton {
    private static Singleton singleton = null;

    private Singleton(){}

    public static Singleton getInstance(){
        if(singleton == null){
            singleton = new Singleton();
        }
        return singleton;
    }
}
```
참고 Multi Thread를 해결하는 방법으로 Lazy Initialize, Double Checked Locking, Lazy Holder ... etc 


**싱글톤을 안티패턴로 보는 이유**
> 안티패턴 <br> 실제로 많이 사용되는 패턴이지만 비효율적이거나 비생산적인 패턴.
1. 객체 지향과 맞지 않다
    - 싱글톤의 사용은 **전역 상태**를 만들기 때문에 바람직하지 않다. 
        - 아무 객체나 자유롭게 접근하고 수정, 공유할수 있는 전역상태를 갖는것은 객체지향 프로그래밍에서 지양해야할 모델이다.
    - 싱글톤은 private 생성자를 갖고 있기 때문에 **상속을 할 수 없다**. (마찬가지로 enum도 상속이 불가하다)
    - 싱글톤으로 만든 객체의 역할이 복잡해질수록 해당 싱글톤을 사용하는 **다른 객체간의 결합도가 높아**져 OCP 원칙이 위배될 수 있다.
    - 의존관계상 클라이언트가 **구체 코드에 의존하므로 DIP 위반** ex) 구현클래스.getInstance();
2. Test하는데 어려움이 있다.
    - 자원을 공유하고 있기 때문에 매번 인스턴스 상태를 초기화 시켜줘야함. 어플리케이션 전역에서 상태를 공유하기 때문에 테스트가 제대로 수행되지 않음
    - MoctTest 역시 만들어지는 방식이 제한적이기 때문에 해당 타입을 인터페이스로 정의한 후 구현해서 만든 싱글톤이 아니라면 해당 싱글톤 인스턴스를 Mock Object로 대체할 수 없다.
    (Mockito는 정적 메서드를 Mock할 수 없어서 가짜(Mock)를 주입하기 어렵지만 Static 메서드를 Mocking 할 수 있는 Power Mock 같은 도구를 사용하면 가능해진다.)
3. 서버 환경에서 싱글톤이 하나만 만들어지는 것을 보장할 수 없다.
    - 생성자를 private하게 만들어도 **Reflection을 통하여 하나 이상의 오브젝트**가 만들어질 수 있다.
    - 여러개의 JVM에 분산 설치가 되는 경우 각각 **독립적으로 오브젝트가 생기기 때문**에 싱글톤으로서의 가치가 떨어진다.

따라서, 이런 단점들을 해결 및 보완해주는 **Spring F/W를 이용한 싱글톤 사용을 권장**합니다.

**Comment by miyeon396** [comment]
감사합니다
