### ISSUE TITLE
[item #04] 인스턴스화를 막기 위한 방식 중 선호하는 방법?

### ISSUE THREAD

**Issue by hailey21** [now-study/study-effective-java#15]
책에서는 추상 클래스로 만드는 경우에 인스턴스화는 가능하지만 의미없는 코드가 생성되어 private 생성자를 완벽한 방법으로 추천하고 있습니다.
그러나 사실 생성자가 분명 존재하는데 호출할 수 없어 적절한 주석을 달아야 하는 둥 불편한 느낌이 있습니다. 

그래서 대충 찾아보니 스프링 프레임워크에 포함된 유틸 클래스들은 추상클래스로 만든 경우가 훨씬 많았고 
자바의 유틸은 (이름이 명확히 유틸이 아닌 경우가 많아보여서 정확히 확인하지는 못했지만)
private 생성자를 선언한 경우가 조금 더 있었던 것 같습니다. 

희진님의 발표에 따라 의미 없는 질문이 될 수도 있겠지만, 두 방식에 대해 어떤 쪽을 선호하시는지 의견을 듣고싶습니다.

**Comment by Heezzan** [comment]
private 생성자 만들어서 에러 던지는게 좋은데 @UtilityClass 가 동일한 역할을 하니 @UtilityClass 를 사용하도록 하겠습니다~

**Comment by daeho-ro** [comment]
@UtilityClass 또는 @NoArgsConstructor(access = AccessLevel.PRIVATE) 어노테이션이 있음.
