### ISSUE TITLE
[item #03] 싱글턴 클래스의 역직렬화는 말로만 역직렬화인건가요?

### ISSUE THREAD

**Issue by Heezzan** [now-study/study-effective-java#16]
싱글턴 클래스를 직렬화 하려면 단순히 Serializable 을 구현한다고 선언하는 것만으로는 부족하다. 모든 인스턴스 필드를 일시적(transient) 이라고 선언하고 readResolve 메서드를 제공해야 한다. 이러지 않으면 직렬화된 인스턴스를 역직렬화할 때 마다 새로운 인스턴스가 만들어진다.

readResolve 메서드를 확인하면 그냥 INSTANCE 를 리턴하는데요, 그러면 역직렬화(바이트로 변환된 객체를 다시 객체로 변환) 를 한다기보다 단순하게 어차피 인스턴스가 하나 뿐이니 그것을 리턴한다고 생각하면 될까요? 바이트 -> 객체 변환 과정이 없는 것 같아서요 

추가로 함수같은 무상태 객체가 왜 싱글턴의 대표적인 예시인지 궁금합니다.. 제가 생각하는 함수는 클래스의 메소드였는데...

**Comment by miyeon396** [comment]
직렬화된 인스턴스를 역직렬화 할 때마다 새로운 인스턴스가 만들어져서 직렬화에 사용한 인스턴스와는 전혀 다른 인스턴스가 되기때문에 싱글턴이 보장이 안된다.
그렇기 때문에 readResolve 메서드로 미리 생성된 INSTANCE를 리턴하도로 구현함.

-> 희진님 말씀하신 것 같이 단순히 인스턴스는 하나뿐이니 동일한 인스턴스를 단순 리턴하도록 구현하는 것이 맞아 보입니다.

추가 질문에 대한 답변으로는 얼핏 확인하기에 추상 메서드들을 담은 인터페이스의 인스턴스를 함수라 칭하는 것 같은데.... 이 부분은 좀 더 같이 확인을 해봤으면 합니다. ㅜ.ㅜ

**Comment by miyeon396** [comment]
@stateless , @singleton 애노테이션의 차이를 한번 찾아보세요 by @daeho-ro
