### ISSUE TITLE
[item #06] 자바 삼항연산자에서 NPE가 발생하는 경우 - 오토박싱

### ISSUE THREAD

**Issue by hailey21** [now-study/study-effective-java#18]
아이템 6을 읽다가 질문은 아니고 재밌어보여서 가져왔습니다.
아래코드는 NullPointerException이 발생합니다.

```java
package com.soojung.effectivejava;

public class Item6AutoBoxing {

    public static void main(String[] args) {
        Long a = null;
        Long b = false ? 0L : a;
    }
}
```
한번씩 가볍게 읽어보면 좋을거같아서 가져왔어요...
참조 : https://velog.io/@skyepodium/%EC%9E%90%EB%B0%94-%EC%82%BC%ED%95%AD-%EC%97%B0%EC%82%B0%EC%9E%90%EC%97%90%EC%84%9C-Null-Pointer-Exception%EC%9D%B4-%EB%B0%9C%EC%83%9D%ED%95%9C%EB%8B%A4%EA%B3%A0

**Comment by hailey21** [comment]
저는 생각도 못했어서 올려봤는데 다들 아는부분이시면 많은 이해를 부탁드립니다..ㅋㅋㅋㅋㅋ

**Comment by golch** [comment]
쩐다 ㅋㅋㅋ 전혀 몰랐습니다

**Comment by daeho-ro** [comment]
뭔가 그냥 생각하는 것과 다르게 에러가 나는게 신기하긴 하네요... 저도 처음 봅니다.
