### ISSUE TITLE
[item #07] 리스너와 콜백의 메모리 누수 방지

### ISSUE THREAD

**Issue by daeho-ro** [now-study/study-effective-java#19]
일단 리스너와 콜백 자체가 비동기 처리를 위한 것으로 알고만 있을 뿐, 우리 서비스에서는 잘 사용하지 않는 방법이라서 개념 자체가 좀 생소한 면이 있습니다. 본문에서 이러한 것들이 명확하게 해지하지 않는다면 메모리 누수가 발생할 수 있다고 하는데, 이 해지의 개념이 무엇일까요?

**Comment by Heezzan** [comment]
GC의 대상이 될 수 있도록, 즉 객체에 유효한 레퍼런스가 없도록 하는 것이 해지의 개념이라 생각합니다. 
null 처리가 그 예가 될 수 있을 것 같습니다.

사실 리스너와 콜백에 대해서 느낌만 알고 있었는데, 자바에서 리스너, 콜백이라고 하니 낯설었는데요..
찾아보니 메소드가 어떤 이벤트에 의해 실행되는 경우를 의미하는 것 같습니다. 그런데 그 메소드가 주로 interface 를 상속받아 구현되어 있고요.
저희 프로젝트에선 @RabbitListener 가 대표적으로 리스너를 사용하는 예시라고 생각을 하는데
그럴 일은 없겠지만 더 이상 큐를 사용하지 않는 경우 리스너의 큐에 널을 할당하는 것이 명확하게 해지를 하는 것이라 생각을 해봤습니다.
 
또 람다와 같은 함수형 인터페이스를 구현하여 콜백 방식을 사용할 경우엔 메모리 누수의 가능성에서 벗어날 수 있다고 생각하는데 제 생각이 맞는지 의견이 궁금합니다.
