### ISSUE TITLE
[item #06] JVM 동작 방식

### ISSUE THREAD

**Issue by miyeon396** [now-study/study-effective-java#22]
책 34페이지 중간 부분을 보면

> 요즘의 JVM에서는 별다른 일을 하지 않는 작은 객체를 생성하고 회수하는 일은 크게 부담되지 않는다.

라고 설명하고 있습니다. 이때 JVM이 작은 객체를 생성하고 회수하기까지의 간단한 Flow를 알고 싶습니다.
또한 책에서 굳이 `작은 객체`라고 강조를 하던데.. `큰 객체`, `작은 객체`를 나누는 이 기준이 무엇이며, 만약에 기준이 존재하고 객체의 종류별로 JVM 동작 방식이 상이하다면 큰 객체를 생성하고 회수하는 Flow도 알고 싶습니다.

질문 요약
1.  JVM의 작은 객체 생성-회수 Flow
2. JVM내의 작은 객체, 큰 객체 구분 기준이 존재하는가 한다면 어느 기준
3. 2번이 존재 한다면 각각의 생성-회수 Flow

**Comment by golch** [comment]
1. 객체의 생성-회수 과정은 가비지컬렉터에 대한 이 설명을 보시면 좋을것 같습니다. https://coding-factory.tistory.com/m/829
2. 작은 객체, 큰 객체의 일반적인 구분은 없는것 같아요. 그런데 찾다보니까 TLAB 이란게 있어서 객체 크기에 따른 튜닝은 가능한것 같습니다. 저도 이정도까지는 한번도 안써봐서, 얼만큼 성능에 도움이 되는지는 잘 모르겠지만요. https://blog.naver.com/kbh3983/220995694888
