### ISSUE TITLE
[item #06] 어댑터 예시가 이해가 되지 않습니다. 

### ISSUE THREAD

**Issue by Heezzan** [now-study/study-effective-java#23]
객체가 불변이라면 재사용해도 안전함이 명백하다. 하지만 훨씬 덜 명확하거나, 심지어 직관에 반대되는 상황도 있다. 어댑터를 생각해보자. 어댑터는 실제 작업은 뒷단 객체에 위임하고, 자신은 제 2의 인터페이스 역할을 해주는 객체다. 어댑터는 뒷단 객체만 관리하면 된다. 즉, 뒷단 객체 외에는 관리할 상태가 없으므로 뒷단 객체 하나당 어댑터 하나씩만 만들어지면 충분하다. (33p)

이 부분에서 어댑터 예시가 왜 나온건지 모르겠습니다. 어댑터가 불필요해 보이는 객체이지만 그래도 사용한다 이런 의미인걸까요..?

**Comment by golch** [comment]
어댑터 패턴이란걸 잘 몰라서 찾아봤어요. https://blog.naver.com/dktmrorl/222084011455
제가 책을 읽으면서 해석한건, "어댑터 패턴으로 구현할때 어댑터 객체 하나에 Adaptee (위 블로그에서는 Adaptee라고 표현했는데, 영문으로는 backing object 라고 되어있네요. 책에서는 뒷단 객체로 번역한것 같아요.) 객체 하나로 구현하는게 좋다. 그렇지 않고 객체 여러개를 생성하도록 구현할 수도 있지만 그렇게 하는 이득이 없다." 이거에요.
혹시 다르게 읽으신분이 있다면 알려주시기 바랍니다.

**Comment by daeho-ro** [comment]
뒷단 객체 외에는 관리할 상태가 없으므로, 불필요하게 뷰 객체를 여러개 만들 필요가 없이 항상 뷰 객체는 하나만 존재해도 되고 이로써 불필요한 객체 생성을 피하라는 의도로 보였습니다. 그래서 Map 인터페이스의 keySet을 예로 들고 있고요.

**Comment by hailey21** [comment]
객체가 불변인 경우라면 재사용 해도 안전하다. 
-> 그러나 어댑터는 가변 객체로 뒷단 객체를 제어함
-> keySet을 여러 번 호출해서 받은 setA, setB라는 어댑터(뷰)가 있는 경우 하나를 수정하면 둘은 같은 객체이기 때문에 다른 하나도 자동으로 바뀜, 수정하면 연결된 Map 객체에도 영향을 미침 

수정한 내용이 다른 객체에 반영되고 모두 똑같은 Map을 대변해야 하기 때문에
1. 가변 객체인 경우에도 뒷단 객체 상태 제어 외에는 역할이 없는 경우에는 재사용해도 괜찮고, 
2. 직관과 다르게(일반적으로 가변객체는 반환한 객체중 하나를 수정하면 각자가 개별 인스턴스로 영향을 미치지 않을 것으로 예상하므로) 재사용해도 안전하다는 뜻으로 나온 예시 같습니다.
