### ISSUE TITLE
[item 07] 간단한 캐시를 구현한 예제코드를 보여주세요.

### ISSUE THREAD

**Issue by golch** [now-study/study-effective-java#24]
책에 stack 을 간단히 구현한 예제코드는 들어있는데, 캐시를 구현한 예제코드는 없네요.
간단한 코드를 작성하여 공유해주시면 좋겠습니다.

**Comment by Heezzan** [comment]
책에서 배열을 사용하여 stack 을 간단하게 구현한 것 처럼 Map 을 사용하여 캐시를 간단하게 구현할 수 있습니다.
Map 을 사용하여 캐시를 구현하는 방법이 저희가 기존에 사용하는 Map 사용법과 크게 다르지 않다고 생각이 들어, 책에서 권장하는 WeakHashMap 을 사용한 방법을 찾아보았습니다.

```
private static void weakHashMapCache() throws InterruptedException {
        Map<Integer, String> cache = new WeakHashMap<>();

        IntStream.range(0, 1000).forEach(i -> weakHashMap.put(i, Integer.toString(i)));
        System.out.println("before gc run weakHashMap size : " + weakHashMap.size());
        System.gc();
        Thread.sleep(5000);
        System.out.println("After gc run weakHashMap size : " + weakHashMap.size());
}
```

위의 코드를 실제 실행시켰을 때 다음과 같은 결과가 나옵니다.
(jvm option 으로 -verbose:gc 를 추가하여 실행하여 gc log 까지 포함한 결과입니다.)

[0.005s][info][gc] Using G1
before gc run weakHashMap size : 1000
[0.047s][info][gc] GC(0) Pause Full (System.gc()) 5M->2M(28M) 2.484ms
After gc run weakHashMap size : 128

WeakHashMap 을 생성하여 사용하였을 때 별도로 Map 에서 제거하는 작업이 이뤄지지 않았더라도 map 의 사이즈가 준 것을 확인할 수 있습니다.

그런데 gc를 실행시킨 뒤 5초 후 확인했을 때 맵의 사이즈가 주는 것을 확인할 수 있는데, gc 만 실행시키거나, 5초만 기다리거나, 둘의 순서를 바꿔 실행시킬때는 맵의 크기가 동일하게 유지되던데 이 부분은 왜 그런건지 잘 모르겠습니다ㅠ

**Comment by daeho-ro** [comment]
@Heezzan 님, 

아무리 WeakHashMap이라고 하더라도 방금 집어넣은 키-밸류 쌍을 GC에서 바로 삭제한다는 부분이 좀 어색하죠. 그래서 좀 더 알아봤는데, 위와 같이 임의로 생성한 Integer 키는 0부터 999까지의 값을 가질텐데요. 이 중에서 0부터 127까지의 값은 Integer 클래스에서 사전에 생성해둔 캐시로부터 참조되기 때문에 삭제되지 않지만, 그 외의 값들은 키에 대한 참조가 존재하지 않기 때문에 GC 대상이 되는 것으로 보입니다. 

위 예제를 아래와 같이 바꿔보면 GC 후에도 사이즈가 유지되는 것을 확인할 수 있습니다.
```java
    public static void main(String[] args) {

        Map<Integer, String> weakHashMap = new WeakHashMap<>();

        List<Integer> list = new ArrayList<>();
        for (int i = 0; i < 1000; i++) {
            list.add(i);
        }
        list.forEach(i -> weakHashMap.put(i, Integer.toString(i)));
        System.out.println("before gc run weakHashMap size : " + weakHashMap.size());
        System.gc();
        try {
            Thread.sleep(5000);
        } catch (Exception e) {
            // do nothing
        }
        System.out.println("after gc run weakHashMap size : " + weakHashMap.size());
    }
```

또한, WeakHashMap에서 GC 대상은 Map의 키를 통해서 판별되기 때문에 캐시의 목적과는 사뭇 다릅니다. 다음 문서를 참고하시면 좋겠습니다. 대안으로는 `Map<K,SoftReference<V>>` 등이 제시되고 있네요.
[Java's WeakHashMap and caching: Why is it referencing the keys, not the values?][1]


 [1]: https://stackoverflow.com/questions/1802809/javas-weakhashmap-and-caching-why-is-it-referencing-the-keys-not-the-values
