### ISSUE TITLE
[item 09] 우리가 업무를 하면서 만날수 있는 꼭 회수해야하는 자원이 어떤게 있을까요?

### ISSUE THREAD

**Issue by golch** [now-study/study-effective-java#25]
언뜻 떠오르지 않아서 같이 생각해보면 좋을것 같아서 질문을 올립니다.

**Comment by hyojae93** [comment]
일반적으로 자원 회수가 필요한 경우는 IOException이 생길만한 경우에 많이 사용하는 것으로 보이고
외부에 있는 자원을 쓰는 경우인 커넥션을 맺거나 파일, 스트림을 사용하여 정보에 엑세스 하는 경우에
메모리로 가져와 사용 후 close를 통하여 연결을 해제하는 등 자원 회수가 필요합니다.
