### ISSUE TITLE
[item #10] 표준형 비교

### ISSUE THREAD

**Issue by miyeon396** [now-study/study-effective-java#26]
63페이지 아랫부분을 보면

> 앞서의 CaseInsetnsitiveString 예처럼 비교하기가 아주 복잡한 필드를 가진 클래스도 있다. 
> 이럴때 그 필드의 표준형(canonical form)을 저장해둔 후 표준형끼리 비교하면 훨씬 경제적이다.

라는 내용이 있는데, 해당 내용에서 이야기하는 표준형의 정확한 의미와 표준형을 사용한 간단한 비교 예시를 알고 싶습니다~

**Comment by golch** [comment]
표준형 (canonical form) 이라는 것은 자바에서 이야기하는건 아니고, 프로그래밍 언어 전반에서 다루어지는 개념인것 같아요.
어떤 사람은 canonical class 라는 것이 반드시 특정 조건을 만족해야 한다고 하고, 다른 사람은 그건 그냥 standard 의 다른 말일뿐 딱 정해진건 아니다 라고 하네요.

아래 링크의 스택오버플로 질문의 답변에 보면 File 경로를 예시로 들고 있어요. 절대경로 상대경로 등 같은 값인데 다른 형태가 있을때 하나를 standard (canonical) 로 정해놓으면 비교할때 수월하다 정도의 의미인것 같습니다.

https://incusdata.com/blog/canonical-classes-in-java
https://stackoverflow.com/questions/280107/what-does-the-term-canonical-form-or-canonical-representation-in-java-mean
