### ISSUE TITLE
[item #02] 자바 빈즈 패턴에서 스레드 안전성 관련

### ISSUE THREAD

**Issue by miyeon396** [now-study/study-effective-java#3]
책 16페이지 하단 부분에 자바 빈즈 패턴에서 스레드 안전성을 얻으려면 프로그래머가 추가 작업을 해줘야만 한다고 얘기하는데,
스레드 안전성을 얻기 위해 어떤 추가작업을 해줘야하는지 궁금합니다

**Comment by daeho-ro** [comment]
자바 빈즈 패턴에서 getter, setter 방식은 기본적으로 클래스 변수를 불변으로 지정할 지정할 수 없기 때문에 일관성이 깨지는 문제가 발생하게 됩니다. 게다가, 언제 객체가 완성된 것인지를 파악하기도 어렵습니다. 반복적으로 메서드를 호출해서 객체를 완성하게 되면 완성했다는 별도의 작업을 해주기 전에는 객체의 완성을 장담할 수 있습니다.

이러한 이유로, 멀티 쓰레드 작업시에 객체의 일관성과 완성을 장담할 수 있다록 별도의 조치가 필요합니다.

1. 멀티 쓰레드 작업 도중에 객체의 일관성을 유지하기 위해서 `synchronized` 이용 - 말 그대로 getter, setter를 멀티 쓰레드에서 작업시에 락을 걸어서 해당 변수에 대한 쓰레드 안정성을 확보하기 위함입니다.
2. 객체가 완성되었으면 immutable로 변경하거나 freeze 메서드를 추가하여 객체 잠금 - 객체가 변경되지 않도록 새로운 immutable 객체를 만들거나 freeze 메서드를 추가해서 객체의 변경을 방지합니다.

예시 코드로는 freeze 메서드를 추가하여 사용하는 방법을 적어봤습니다.

```java
public class Test {

    private int a;
    private boolean freeze;

    private synchronized int getA {
        return this.a;
    }

    private synchronized void setA(int a) {
        if (isFreeze()) {
            throw new Exception("객체가 잠겼습니다");
        }
        this.a = a;
    }

    private synchronized boolean isFreeze {
        return this.freeze;
    }

    private synchronized void freeze {
        this.freeze = true;
    }
}
```

물론, 보는 바와 같이 freeze 메서드 방식은 기존 객체에 대한 많은 변경을 요구하기 때문에 불변 객체를 필요로 한다면 역시 빌더 패턴을 이용하는 것이 월등히 유리합니다.

**Comment by hailey21** [comment]
`volatile` 키워드를 쓰는 방법도 있다고 하네요. 
volatile 키워드를 추가하게 되면 메인 메모리를 통해 저장하고 읽도록 해서 변수를 공유할 수 있을 것 같아요.
구현에 따라서 선택할 수 있을 것 같고, 우리 배치에서 가끔 보이던 해당 키워드가 그런 목적으로 쓰였던거같습니다.

**Comment by daeho-ro** [comment]
답변을 보고 추가적으로 `volatile` 키워드에 대해서 알아봤는데, 이 키워드는 변수의 값을 메인 메모리에 저장하고 읽어들임으로써 `atomicity`,  즉 원자성을 보장한다고 합니다. 그래서 멀티 쓰레드에서 읽고 쓰는 것에 대해서는 쓰레드 사이에 최신 값을 잘 공유해준다고 합니다.

다만, 변수의 값을 읽어서 원자성을 보장하지 않는 오퍼레이션을 거쳐 다시 저장하는 작업이 있으면 문제가 될 수 있다고 합니다. 예를 들어, 작업 카운트를 체크하는 `int` 타입의 카운터 변수 `counter`가 있을 때, 작업을 increment하게 카운트하기 위한 `counter++` 연산은 원자성을 보장하지 않습니다. 왜냐하면, 
1. 연산이 한 번에 이루어지지 않고 `counter` 변수를 읽어서
2. 해당 변수에 +1을 한 다음에 다시 쓰는 작업이 이루어지기 때문에
작업은 두 번에 걸쳐서 이루어지며 원자성을 보장하지 못하게 되는 것입니다. 이처럼 원자성이 보장되지 않으면 1번 쓰레드에서 해당 변수를 읽은 직후에 2번 쓰레드에서도 동시에 읽을 수 있습니다. 그러면 두 쓰레드에서 각각 카운트를 +1을 하지만 결과적으로는 +2가 되지 않고 +1만 되는 현상이 벌어지게 됩니다. 이와같이 중간에 쓰레드 간섭이 발생해서 카운터가 정상적으로 이루어지지 않을 수가 있기 때문에, 원자성이 보장되지 않는 작업이 존재한다면 `volatile`을 사용하더라도 멀티 쓰레드에서의 안정성을 보장하지 못하는 것입니다.

멀티 쓰레드의 안정성을 담보하려면 이러한 연산을 모두 `AtomicReference`, `AtomicInteger`와 같은 클래스를 통해서 원자성을 보장하는 방법을 이용하거나 약간의 성능을 포기하고 배타적인 실행을 추가하는 `synchronized` 키워드를 사용하는 것이 안전하다고 하네요.
