### ISSUE TITLE
[item #11] 우리가 실무에서 사용하는 model 중에서 hashCode 를 재정의해서 사용할만한 case 가 어떤게 있을까요?

### ISSUE THREAD

**Issue by golch** [now-study/study-effective-java#30]
이것은 사실 item10 의 equals 도 마찬가지 문제라서 같이 생각해보자는 차원에서 질문드립니다.
정답이 딱히 없을것 같으니 그동안 업무를 하면서 생각했던것들 위주로 토론해보면 좋을것 같아요.

**Comment by miyeon396** [comment]
실무 사용 예시로 형주님 말씀 주신 svcGrp 모델에 pk들 override 해서 사용할 수 있는 예시가 있었고, 이외에도 같이 이야기 했던 것과 같이 더 많은 예시가 있을 것으로 보입니다. 따라서 equals와 hashcode custom 구현이 필요한 경우 item 10, 11 잘 고려 개발되면 좋을 것 같슴다
