### ISSUE TITLE
[item #13] 클론 규칙이 생성자 연쇄 매커니즘과 비슷하다는 부분에 대해

### ISSUE THREAD

**Issue by hailey21** [now-study/study-effective-java#32]
P.78
> clone 매서드가 super.clone 이 아닌, 생성자를 호출해 얻은 인스턴스를 반환해도 컴파일러는 불평하지 않을 것이다. 하지만 이 클래스의 하위 클래스에서 super.clone을 호출한다면 잘못된 클래스의 객체가 만들어져, 결국 하위 클래스의 clone 메서드가 제대로 동작하지 않게 된다.

의 주석으로 

> ..(생략) super.clone을 연쇄적으로 호출하도록 구현해두면 clone이 처음 호출된 상위 클래스의 객체가 만들어진다.

부분이 잘 이해가 가지 않습니다. 관련내용을 블로그로 더 찾아보긴 했는데 설명해주시면 감사하겠습니다.
물론 발표 내용에 포함되어 있다면 스터디시간에 같이 공유해주셔도 좋습니다!

**Comment by daeho-ro** [comment]
> 클래스 B가 클래스 A를 상속할 때, 하위 클래스인 B의 `clone`은 B 타입 객체를 반환해야 한다. 그런데 A의 `clone`이 자신의 생성자, 즉 new A(...)로 생성한 객체를 반환한다면 B의 `clone`도 A 타입 객체를 반환할 수밖에 없다.

본문과 주석을 요약하자면, `clone` 메서드가 반환하는 객체를 `super.clone`이 아닌 생성자를 호출해서 얻은 인스턴스라고 하더라도 타입이 잘 맞기 때문에 컴파일러에서 불평하지 않을 것이라고 하고 있습니다. 그렇지만 해당 클래스의 자식 클래스에서도 생성자를 이용하지 않고 `super.clone`을 사용하게 된다면 자식 클래스에서는 부모 클래스의 `clone`을 호출하게 될 것이고, 생성자 호출에 따라서 자식 클래스 인스턴스가 아닌 부모 클래스 인스턴스가 반환되는 문제가 생겨서 `clone` 메서드에 문제가 생길 수 있음을 얘기하고 있습니다.

> 달리 말해 `super.clone`을 연쇄적으로 호출하도록 구현해두면 `clone`이 처음 호출된 상위 클래스의 객체가 만들어진다.

저는 이 부분이 심지어 _하위 클래스의 객체가 만들어진다._ 라고 나와서 혼란스러웠는데... 달리 말해 뒷부분도 결국 생성자 방식으로 부모 클래스를 정의하고 자식 클래스들이 `super.clone`을 연쇄적으로 호출하도록 구현해두면 생성자 방식으로 구현되는 상위 클래스가 만들어진다는 것을 요약하는 것 같습니다. 정상적으로 `clone`을 구현했다면, 그리고 연쇄 호출이 정상적이었다면 `clone`이 호출된 클래스의 객체가 만들어졌겠죠.
