### ISSUE TITLE
[item #14] Comparator/Comparable 인터페이스

### ISSUE THREAD

**Issue by hailey21** [now-study/study-effective-java#33]
두 인터페이스 간의 차이점은 어떤 것이 있을까요?

Comparable 인터페이스를 쓰려면 compareTo 메소드를 구현해야하고, 
Comparator 인터페이스를 쓰려면 compre 메소드를 구현해야 한다는 점 외에 어떤 상황에서 어떤 인터페이스를 선택하여 구현하면 좋을지 궁급합니다.

**Comment by Heezzan** [comment]
Comparable 의 compareTo 메서드는 파라미터를 하나만 받아 자기 자신과 매개변수의 객체를 비교하고,
Comparator 의 compare 메소드는 파라미터를 두 개 받아 두 매개변수 객체를 비교합니다.

책에서는 Comparable 을 구현하지 않은 필드나 표준이 아닌 순서로 비교해야할 경우 즉, Comparable 에 구현된 순서대로 정렬을 하지 않을 경우 Comparator 를 사용하라고 나와있습니다.
Collections.sort() 의 경우 인자로 받은 객체가 Comparable 을 구현한 경우 정의된 compareTo 에 따라 정렬을 하게 되는데, 그렇지 않은 경우 직접 인자로 Comparator 을 넣어줘야 합니다. (Comparator 의 경우 구현해놓고 사용하는것 보단 익명클래스로 생성해서 사용하는 것 밖에 보지 못했습니다,,)

따라서 일반적으로 객체 정렬의 기준을 둘 때에는 Comparable 을 사용하고, 그렇지 않은 경우에는 Comparator 을 사용하는 것으로 생각했습니다!
