### ISSUE TITLE
[item #15] public static final 배열 필드

### ISSUE THREAD

**Issue by miyeon396** [now-study/study-effective-java#35]
본문 99페이지의 하단 부분에

> 길이가 0이 아닌 배열은 모두 변경 가능하니 주의하자. 
> 따라서 클래스에서 public static final 배여 필드를 두거나 이 필드를 반환하는 접근자 메서드를 제공해서는 안된다.
> 이런 필드나 접근자를 제공한다면 클라이언트에서 그 배열의 내용을 수정할 수 있게 된다.

라는 내용이 있습니다.

해당 설명이 static final 변수여도 array 타입이라면 배열 요소를 추가하거나 삭제하는 코드를 작성하면 추가, 삭제가 가능하다고 이해를 했는데 이게 맞게 이해 한 것인지
array의 경우 변형이 가능한게 일부로 의도한 것인지 아님 개발 허점인지, array만 이런 이슈가 있는지 궁금합니다.

제가 기억하는 개발 케이스는 특정 클래스에서만 사용하기 때문에 private static final BATCH_ST_DT_ARR = {"09", "18"}; 이런식으로 사용하긴 했다만, 
만약 저 BATCH_ST_DT_ARR 다른 클래스에서도 사용했다면 public 으로 공통으로 선언해서 공유하며 사용했을 텐데.. 
뭔가 예외적으로 특이한 경우인 것 같이 설명이 되어 있어 관련 내용에 대해 가능하다면 좀 더 알아보고 싶어 이슈 작성했습니다.

**Comment by hyojae93** [comment]
말씀하신 것과 같이 public static final 기본 타입이 아닌 Array와 같은 경우
final 특성상 해당 객체를 직접적으로 변경하는 것은 할당된 주소를 변경하는 행동이기 때문에 불가능하지만 
각각의 요소를 변경하는건 주소값을 변경하는 것이 아니기 때문에 각 배열의 요소는 변경 가능하다고 이해하였습니다.

```
class BatchSchedule {

    public static final String[] BATCH_ST_DT_ARR = {"09", "18"};

}

class BatchScheduleMain {

    public static void main(String[] args) {
        System.out.println(BatchSchedule.BATCH_ST_DT_ARR[0]); // 09
        BatchSchedule.BATCH_ST_DT_ARR[0] = "10";
        System.out.println(BatchSchedule.BATCH_ST_DT_ARR[0]); // 10

    }

}
```


다른 클래스에서 public 하게 공유하여 사용하려면 책에서 나온 예시처럼 불변 List를 선언하거나 복제를 하는 방법이 있습니다.

```
class BatchSchedule {

    private static final String[] BATCH_ST_DT = {"09", "18"};

    // 1
    public static final List<String> BATCH_ST_DT_ARR = Collections.unmodifiableList(Arrays.asList(BATCH_ST_DT));
    
    // 2
    public static String[] startTime(){
        return BATCH_ST_DT.clone();
    }

}
```
