### ISSUE TITLE
[item #14] 타입이 다른 경우의 Comparator, Comparable

### ISSUE THREAD

**Issue by daeho-ro** [now-study/study-effective-java#36]
책에서 다루는 Comparator, Comparable은 항상 같은 타입에서만 동작하나요? 다른 타입의 순서는 어떻게 비교할 수 있을까요? 예컨데 int와 float을 안전하게 비교하기 위한 compare 메서드라던가... 이런건 본 적이 없는 것 같아서요. 타입 캐스팅이 되어서 필요가 없는건지...

**Comment by Heezzan** [comment]
Comparator, Comparable 이 같은 객체 타입에서만 동작하는 것인지 물어보시는거라면 (아닌 것 같지만..)
서로 다른 객체가 비교할 객체 필드를 공통으로 가지는 인터페이스를 가질 경우 서로 다른 객체의 비교가 가능합니다.

객체 필드의 비교 타입을 말씀하시는 거라면, 권장하지 않는 방식인 것 같습니다.
객체 필드를 비교할 때 관계 연산자를 사용하기보단, compare 메서드를 사용하라 했는데 이 경우 같은 타입간의 비교만 가능합니다. 

다른 타입간의 비교가 말씀해주신 것 처럼 int, float 간의 비교밖에 떠오르지 않아 이상하지만 코드를 만들어 봤습니다..
(int, float 간의 정확한 비교는 가능하다고 합니다. https://stackoverflow.com/questions/41653576/is-it-safe-to-compare-a-float-and-an-int-in-java)

```
public class LiveThings implements Comparable<LiveThings> {

    String type;
    int humanAge;
    float dogAge;

    @Override
    public int compareTo(LiveThings o) {
        float self = "H".equals(this.type) ? humanAge : dogAge;
        float param = "H".equals(o.type) ? o.humanAge : o.dogAge;

        if (param == self) {
            return 0;
        } else {
            return self > param ? 1 : -1;
        }
}
```
사실 이렇게 코드를 작성하기 전에 return sefl-param  과 같이 작성했는데.. -0.5 를 int 로 변환하는 과정에서 0이 되어서 원하는데로 정렬이 되지 않는 문제가 있었습니다,,
