### ISSUE TITLE
[item #18] 상속의 사용처

### ISSUE THREAD

**Issue by miyeon396** [now-study/study-effective-java#37]
상속은 is-a(ex coffee is a coffeeBeverage), 조합은 has-a(ex WinningLotto has a Lotto )
구현은 기능 명세이자 구현을 강제하는 경우에 각각 사용한다고 이해하고 있습니다.

이런 룰을 모르고 거의 상속 전도사 격으로 여러 곳에서 사용하여 난해한 코드를 작성해 많이 걷어 내주신 걸 기억을 하는데요
ex) ResourceNotiAnomalyInstanceCostRuleProcess extends ResourceNotiParent / GcpBatchTargetFilter extends GcpTargetFilter
이런 친구들 말고 우리 서비스내에서 상속이 필요한 경우가 있을까요?? 같이 한번 생각을 해보고 싶어서 질문으로 남겨 놓습니다.
또, 상속을 단순히 지양한다는건 비즈니스 관점에서이고 여러 곳에서 중복되는 공통 모델 필드 들?(사이트, 컴퍼니, 리전, 어카운트 등...) 같은 것은 상속으로 써도 괜찮을까요??

**Comment by hailey21** [comment]
상속은 기존 클래스를 이용하여 그것을 특수화한 새 클래스를 쉽게 설계할 수 있다는 점에서 강력한 기능입니다.

그러나 18장 내용과 같이 많은 부작용들이 있는데 주로 복잡한 구조와 그 영향력에 대해 개발자가 인지하기 힘들어서 생기는 문제점 같습니다.
- 캡슐화를 위반한다.
- 설계에 유연하지 못하다.
- 구조가 복잡해질 수록 영향에 대한 예측이 힘들고 사용에 어려움이 생길 수 있음

예로 들어주신 우리 클래스 중에도 ResourceNotiAnomalyInstanceCostRuleProcess extends ResourceNotiParent는 제가 생각했을 때 상속과 어울리지는 않다고 느꼈었는데요, 어떤 기능은 부모에서, 어떤 기능은 자식에서 혼재되어 있는 상황에서 불필요하게 오버라이드 되어 자식 클래스에서는 아무것도 하지 않는 메서드들도 있어 클래스가 잘 설계되지 않았다는 느낌을 받았습니다.

interface상속 말고 구현상속이 적절히 딱 어울리는 경우는 아직 잘 모르겠습니다.
동물 인터페이스를 구현한 개 클래스를 만들고 개 클래스를 상속하는 푸들 말티 비숑 클래스를 만든다..? 
이런식으로 여기저기서 개념적으로는 설명하고 있지만 비즈니스 관점에서는 애매한 부분이 많습니다.
asset usage/performance를 리펙토링 하면서 공통되게 처리되는 부분이 많아 인터페이스와 상위 클래스를 하나 더 만들려고 했다가 애매하게 조금씩 다른 비즈니스 때문에 포기했던 기억이 나네요..

중복되는 모델 필드들의 경우 책에서 예로 든 내부구현 방식에서는 조금 더 자유로운 편이지만 캡슐화 측면에서는 조금 애매하다는 생각이 듭니다.
관용적으로 모델 클래스에서는 필드와 getter setter만 정의해서 사용하고 있지만 강제적으로 제한되어 있는 부분은 없기 때문에 어떤식으로라도 확장해서 쓰려면 쓸 수 있을 것 같습니다.. 

모델 클래스를 상속해서 쓰는 방법은 저도 여기저기서 활용하긴 했었지만 
코드 그 자체의 재활용성보다는 타입을 맞춰서 공통적으로 처리하려고 했던 측면이 강했는데, 
지금 생각해보니 그것도 적절하지 않은 생각이 듭니다. 단순히 타입 체크라면 interface를 활용했어야 했나 싶고요.

상속이 적절한 케이스보다는 컴포지션으로 처리할 수 있으면 가급적 컴포지션으로 처리한다고 생각하고 설계를 하면 좋을 것 같습니다.
