### ISSUE TITLE
[item #18] 컴포지션에 대해 이해한 내용이 맞는지...

### ISSUE THREAD

**Issue by daeho-ro** [now-study/study-effective-java#38]
책에서는 컴포지션의 예제로 Set 인터페이스를 구성요소로 사용하는 ForwardingSet 클래스와 이를 확장한 래퍼 클래스인 InstrumentedSet 클래스를 보여주고 있습니다. ForwardingSet 클래스는 컴포지션을 사용하여 외부에서 유입되는 Set 인터페이스의 메서드들에 대해 기능을 위임하고 래퍼 클래스는 이를 상속하여 특정 기능을 재정의 함으로써 본래의 의도였던 HashSet 상속으로부터 발생할 수 있는 문제들을 회피하고 있습니다. 이 설명이 맞나요?

실제 사용에서는 인터페이스를 대상으로 컴포지션할 경우가 많을지 모르겠습니다. 그래서 만약 위 예제에서 본래 의도였던 HashSet에 대한 컴포지션을 생각해보면 다음과 같이 코드가 작성될 것 같습니다.

```java
public class InstrumentedSet<E> {

    private int addCount = 0;
    private final HashSet<E> s;

    public InstrumentedSet(HashSet<E> s) {
        this.s = s;
    }

    public boolean add(E e) {
        addCount++;
        return s.add(e);
    }
    public boolean addAll(Collection<? extends E> c) {
        addCount += c.size();
        return s.addAll(c);
    }
    public int getAddCount() {
        return addCount;
    }
    ...
}
```

이제 우리 소스를 하나 살펴보면...

```java
@Service
@RequiredArgsConstructor
public class DashboardService {

    private final DashboardFactory factory;
    private final CommonService commonService;

    public DashboardTotalSummaryModel getDashboardSummary(DashboardRequestModel reqModel) {
        ...
        vendors.forEach((vendor, order) -> {
            try {
                DashboardTotalSummaryModel temp = factory
                        .getDashboardDao(Vendor.getVendorByString(vendor))
                        .getDashboardSummary(reqModel);
                if (!ObjectUtils.isEmpty(temp)) {
                    temps.add(temp);
                }
            ...
        }
        ...
        return result;
    }
```

DashboardService는 컴포지션으로 팩토리와 서비스를 받고, 이들에게 내부 기능을 위임하여 사용하는 것처럼 보입니다. 그렇다면, 우리는 이미 진작부터 컴포지션을 아주 잘 사용해왔다고 봐도 되는걸까요? 이번 질문은 제가 위와 같이 이해한 바가 맞는지를 확인하고 싶었습니다.

**Comment by hailey21** [comment]
컴포지션을 잘 사용한 부분이긴 하나 우리가 전부터 잘 사용해왔다고 보기엔 무리가 있는 것 같습니다.ㅠㅠ
의존성을 필드 또는 생성자를 사용하여 주입하는 방식은 스프링을 사용하면 관념적으로 사용하는 사례로 
상속/컴포지션에 대한 깊은 이해가 없이 관성적으로 사용해온 케이스라고 생각합니다. 

이런 부분보다 ResultModel 등 너무 당연하게 상속해서 쓰고 있었던 부분들에 대해서 다른식으로 생각해볼 필요가 있는 것 같습니다.
