### ISSUE TITLE
[item #01] 시그니처란 무엇이고, 그것이 같다는 의미는?

### ISSUE THREAD

**Issue by daeho-ro** [now-study/study-effective-java#4]
본문 9페이지:

> 하나의 시그니처로는 생성자를 하나만 만들 수 있다.

질문:

시그니처란 무엇이고, 그것이 같다는 의미는 무엇을 의미하는 것인지?

**Comment by hyojae93** [comment]
생성자 즉 메서드의 선언부가 메서드 명, 파라미터의 순서, 타입, 개수의 관계를 메서드의 시그니처로 지정하고 
생성자의 시그니처가 같아서는 안되기 때문에 책에서는 파라미터의 순서를 바꿔서 추가 할 수는 있지만
올바른 방법이 아니며, 정적 팩터리 메서드로 바꾸고 명확한 이름을 지어 선언하라고 되어있습니다.

**Comment by daeho-ro** [comment]
이 부분이 강조하고 싶었던건데, 단순히 파라미터의 순서만 보면 문제가 될 수 있어보여요. 왜냐하면, 

```java
public class Test {
    private final String a;
    private final String b;
    private final String c;

    public Test(String a, String b) {
        this.a = a;
        this.b = b;
    }

    // 에러, 들어오는 변수가 a, b인지 b, c인지 구분할 수가 없으므로...
    public Test(String b, String c) {
        this.b = b;
        this.c = c;
    }
}
```

이렇게 생성자 2개가 있을때, 생성자의 인풋으로 들어오는 변수가 뭔지 구분할 방법이 없죠. 위의 예제에서는 2개의 스트링 변수를 받는 2개의 생성자가 있다고 할 때, 어떤 변수에 매핑해야 할 것인지 구분하지 못하므로 결국 중요한 것은 파라미터 *타입*의 순서인 것 같아요.
