### ISSUE TITLE
[item #20] 디폴트 메서드가 추가된 인터페이스와 추상 클래스에 대해 

### ISSUE THREAD

**Issue by hailey21** [now-study/study-effective-java#41]
디폴트 메서드가 일부 포함된 인터페이스에서는 얼핏 추상클래스와 그 모양이 비슷해보입니다.
추상클래스에서의 일반메소드를 구현하여 제공하는 것과 인터페이스에서 디폴트 메소드로 제공하는 것에는 어떤 용도의 차이점이 있을까요?

**Comment by Heezzan** [comment]
상태를 가질 수 있다는 점이 추상클래스와 인터페이스의 큰 차이라고 생각합니다.

추상클래스의 경우 상태를 가질 수 있기 때문에 추상클래스의 일반 메소드에선 상태를 가지는 변수에 접근을 할 수 있고,
인터페이스는 단순 상수만을 가질 뿐 상태를 가질 수 없어서 인터페이스의 디폴트 메소드에서는 이런 상태를 가지는 변수에 접근을 할 수 없습니다. 
메서드에서 상태 접근 여부에 따라 인터페이스의 디폴트 메서드를 사용하거나, 추상 클래스의 일반 메소드를 선택할 수 있다고 생각합니다.

참고) https://www.baeldung.com/java-interface-default-method-vs-abstract-class
