### ISSUE TITLE
[item #21] 문장이 이해가 안가는데...

### ISSUE THREAD

**Issue by daeho-ro** [now-study/study-effective-java#43]
> 한편, 디폴트 메서드는 인터페이스로부터 메서드를 제거하거나 기존 메서드의 시그니처를 수정하는 용도가 아님을 명심해야 한다.

갑자기 이런 내용이 책에서 나오는데, 정확히 어떤 상황에서 뭘 하지 말라는 것인지 잘 이해를 못했습니다.

**Comment by hyojae93** [comment]
인터페이스 기존 메서드를 디폴트 메서드로 변경하여 필수에서 제거하거나 시그니처 파라미터의 변경등의 용도로 사용하지 말라는 뜻으로 이해하였습니다.
저희의 상황에서 생각해 보았을때 동일한 인터페이스로 확장되어지던 서비스가 있는데 
무조건 구현하지 않아도 되는 상황이 생겼을때 혹은 당장 구현해서는 안될때
해당 메서드를 default로 바꾸려고 할 경우가 생길수도 있다는 생각이 들었고
구현하고 있는 클라이언트에서 어떤식으로 서비스를 제공하는지 알 수 없기 때문에 오류를 초래할 수 있습니다.
