### ISSUE TITLE
[item #23] 인터페이스와 추상 클래스 용도에 대해

### ISSUE THREAD

**Issue by hyojae93** [now-study/study-effective-java#44]
책에서 태그 달린클래스를 클래스 계층구조로 변환한 예제에서
추상클래스로 Figure를 선언하였는데
Figure라는 사전적 뜻의 의미와 모양의 일부인 사각형, 원형은 의미상 서로 관계가 있기 때문에 
확장의 의미에서 추상클래스를 사용하는 것일까요?
인터페이스도 구현 클래스와의 의미상 연관 관계는 존재하는 것으로 보이는데
지난번 item #20에서 다뤄졌던 인터페이스와 추상클래스 기능적인 설명 외에 
구현하는 관점이 아닌 사용목적에 따라 먼저 판단을 진행하게 된다면
개념적인 용도의 쓰임상 어떤 사용이 적합할지에 대한 설명부탁드립니다!

**Comment by hailey21** [comment]
책에서 예제로 추상클래스를 만들어 상속받게 했던 이유는 
사각형 원형의 area를 구하는 공통의 기능이 있고 태그 값에 따라 동작이 달라지는 특수한 케이스이기 때문이라고 생각했습니다.
또 마지막 예제에 보면 직사각형의 아주 특별한 케이스로 정사각형 예시를 보여주고 있는데요, 
인터페이스로 구현했다면 직사각형의 생성자를 활용하지 못하고 별도구현을 했어야 했을 것입니다.

예제에서 명백한 계층구조를 보여주고 있고 다른 타입 또는 기능을 확장하지도 않고 있어서 추상클래스로 구현을 했다고 생각을 했습니다..
물론 인터페이스로도 가능하지만 별도 처리를 더 해야 했을 것이고 그게 나쁘지만은 않았을거라고 생각합니다.


우리 업무에서 벤더별 기능 확장을 생각해보면 

vendor 
- aws
- azure .. 

벤더별 사용량 수집을 한다고 했을 때 공통된 기능을 구현해야 하지만 상위 vendor라는 계념에 각 aws azure..등등은 계층구조로는 보기 어려운 부분이 있다고 생각합니다. vendor라고 우리가 일반화시킨 것 뿐이지 같은 부모? 개념을 가지고 있다고 보기는 어렵기 때문입니다. 현재는 벤더로만 구분했지만 기능상으로도 별도로 설계를 했다면 여러 개의 인터페이스가 필요했을 것이고 그러면 다중상속도 필요할 것입니다. 그래서 인터페이스 구현이 더 어울리는 것 같고요.

aws의 특정 리소스들을 수집한다고 했을 때에는 aws sdk를 사용하거나 관련 테이블에 넣는 일련의 과정은 동일하지만 세부 구현이 달라 추상클래스가 더 어울리는 것 같습니다. 또는 골격 구현으로 세부구현만 다르게 해서 빠르게 개발할 수도 있을 것 같습니다.

인터페이스와 추상클래스의 개념에 대해 공부했을 때 인터페이스는 밑그림만 그려진 기본 설계도, 계층구조와 관계 없이 동일한 기능을 구현해야 할 때 사용해야 한다고 이해했고 추상클래스는 관련성이 높은 클래스들 사이에(부모-자식 관계) 코드를 공유하거나 공통으로 가진 메소드와 필드가 많은 경우 사용을 하면 좋을 것 같습니다.
