### ISSUE TITLE
[item #22] 인터페이스 내에서의 상수

### ISSUE THREAD

**Issue by daeho-ro** [now-study/study-effective-java#45]
책에서는 안티 패턴이므로 사용하지 마라고 하지만, 사실 자바에서 허용하지 않을 거라면 애초에 상수 정의조차 못하게 할 수 있었을텐데요.
안티 패턴임에도 불구하고 인터페이스 내에서 상수를 사용해야만 하는 경우가 존재할까요? 골격 구현하고 섞으면 절대 없을것도 같은데...

**Comment by miyeon396** [comment]
인터페이스에서의 상수 사용 자체를 지양한다기보다 인터페이스를 상수 자체로 사용하는 것을 지양하라고 이해를 했습니다.

비슷한 예로 책에 이런 구문도 존재합니다.

> "상수를 공개할 목적에서..., 특정 클래스나 인터페이스에 강하게 연관된 상수라면 그 클래스나 인터페이스 자체에 추가하라"

이런 내용으로 보았을 때, 인터페이스에서 상수 사용 자체는 허용을 하되, 상수만 존재하는 인터페이스인 `상수 인터페이스를 지양`하라는 의미로 들려집니다.

또한 말씀주신대로 골격구현을 사용해서 해당 인터페이스를 구현한 Abstract Class에 상수를 정의하는 방법도 하나의 인터페이스에서 상수를 사용하지 않는 방법이 될 수 있다고 생각이 듭니다.

하지만 반대로 골격 구조가 아닌 인터페이스만이 존재하는 경우. 동시에 공통으로 사용하는 상수가 있는 경우엔 일부 상수 필드를 인터페이스에 정의해 놓아도 되지 않을까라고 생각합니다.
