### ISSUE TITLE
[item #22] 상수 인터페이스는 왜 사용하는 걸까요?

### ISSUE THREAD

**Issue by Heezzan** [now-study/study-effective-java#46]
책에서는 "상수들을 사용하려는 클래스에서는 정규화된 이름을 쓰는 걸 피하고자 그 인터페이스를 구현하곤 한다." 라고 나와있습니다.
다른 내용들은 다 이해가 되는데 이 문장이 이해가 안되서 상수 인터페이스를 어쩌다 사용하게 됐는지? 왜 사용하는지 도저히 이해가 가지 않습니다.. 

대호님 질문과 비슷하다 느껴질 수 있는데, 제가 아이패드로 요리조리 해보다 실수로 이슈가 생성되었는데 삭제가 안되어 별도의 이슈로 질문 드립니다..ㅎ

**Comment by miyeon396** [comment]
음 제가 정확하게 이해한 것인지는 잘 모르겠습니다. 일단 이해한 것 기준으로 답변을 작성 해보겠슴니다.

> In Java, there are two kinds of names: simple and qualified. A simple name consists of a unique identifier while a qualified name is a sequence of simple names separated by dots.

위의 설명에 따르면 자바에는 두가지 종류의 이름이 있으며 simple, qualifed name이 있다고 합니다.
책의 내용에서 설명한 `정규화된 이름`이 `Qualified name`이며 이는 `점으로 구분된 일련의 이름`입니다.

상수들을 사용하려는 클래스에서 이 정규화된 이름을 사용하는 것을 피하기 위해 상수 인터페이스를 사용해서 구현했다고 하는데요

상수 인터페이스 
```java
public interface ConstantsUsingInterface {

    double PI = 3.14159;
    double PLANCK_CONSTANT = 6.62606896e-34;
}
```

이를 구현한 클래스 에서 PI를 출력해 보면 
```java
public class DoTestInterface implements ConstantsUsingInterface{

    public static void main(String[] args) {
        System.out.println("i want pi"+PI);
    }
}
```
이런식으로 단순히 PI라는 변수명 만을 사용하면 오류없이 동작을 하는 것을 볼 수 있습니다.

반대로, 상수 인터페이스 사용 없이 상수가 정의된 Class 하나와
```java
public class ConstantsUsingClass {

    private ConstantsUsingClass() {} //인스턴스화 방지

    public static final double PI = 3.14159;
    public static final double PLANCK_CONSTANT = 6.62606896e-34;

}
```

이를 사용할 다른 테스트 클래스에서 PI를 출력해봅니다.
```java
public class DoTestClass {

    public static void main(String[] args) {
//        System.out.println("i want pi"+PI); //cannot resolve symbol pi
        System.out.println("i want pi"+ConstantsUsingClass.PI);
    }
}
```
Class로 상수를 구현해 놓은 경우 PI만 사용시 `Cannot Resolve Symbol PI` 에러를 뱉고, 앞에 클래스 이름까지 지정을 해줘야합니다.
아마도 이런거를 작성하지 않아도 되는 편리함? 때문에 상수 인터페이스를 썼다고 설명한 것이 아닐까라고 생각을 합니다 ㅎㅎ
