### ISSUE TITLE
[item #01] 정적 팩터리 메서드를 작성하는 시점에는 반환할 객체의 클래스가 존재하지 않아도 된다.

### ISSUE THREAD

**Issue by daeho-ro** [now-study/study-effective-java#5]
본문 11페이지:

> 정적 팩터리 메서드를 작성하는 시점에는 반환할 객체의 클래스가 존재하지 않아도 된다.

질문:

위 내용을 설명할 수 있는 구체적인 예시가 무엇이 있을까요?
본문 내용을 봐도 제가 이해를 잘 못하겠네요. JDBC를 예시로 드는 것 같은데...

**Comment by Heezzan** [comment]
저도 이 부분을 잘 모르겠습니다..
클래스가 존재하지 않으면 컴파일 에러가 발생하지 않나요? 아니면 와일드카드를 사용하는 걸까요..? 아님 전혀 관계 없는 딴 얘기일까요?!

**Comment by hyojae93** [comment]
Class.forName("com.mysql.jdbc.Driver");

// 서비스 접근 API인 DriverManager.getConnection가 서비스 구현체(서비스 인터페이스)인 Connection 반환
Connection connection = DriverManager.getConnection(url, user, password);

@CallerSensitive
public static Class<?> forName(String className)
            throws ClassNotFoundException {
    Class<?> caller = Reflection.getCallerClass();
    return forName0(className, true, ClassLoader.getClassLoader(caller), caller);
}

해당 메소드에서 com.mysql.jdbc.Driver이란 클래스를 찾기 위해 
리플렉션을 이용하여 실행 당시 동적으로 찾아 들어가기때문에 메서드 작성 시점에서는 클래스가 존재하지 않아도 된다고 설명하고 있습니다.
