### ISSUE TITLE
[item #28] 제네릭 배열?

### ISSUE THREAD

**Issue by daeho-ro** [now-study/study-effective-java#51]
본문에서 제네릭을 이용한 배열 예시, `List<String>[]`가 나옵니다. 아마도 지금은 컴파일 에러가 나므로 이와 같은 문법을 사용할 수 없겠지만, 만약에 사용 가능하다고 한다면 이것이 의미하는 것은 무엇인가요? `List<String>`이 엘레먼트로 담겨있는 배열?

코드 28-3 예시에서 오브젝트가 가리키는 의미가 너무 모호해서 이해가 잘 안되네요..

**Comment by hailey21** [comment]
제네릭은 다양한 타입의 객체를 다루는 메소드나 컬렉션 클래스에 컴파일 시 타입체크를 해주는 기능입니다.
그러니까 `List<String>[]`은 스트링 제네릭 배열의 타입을 컴파일 타임에 체크했고 통과했다는 상황을 가정했다고 생각이 됩니다.
우리는 배열이나 리스트나 무의식적으로 개발하는 시점에(=컴파일 타임에) 구체화해서 구현을 하기 때문에 그게 뭐가다른거지? 하고 잘 와닿지 않는 것 같네요..

그런데 관련된 내용을 보다가 HashMap에서 버킷 배열 구현에 제네릭 배열을 사용하는 케이스를 확인할 수 있었는데요, 
```java
transient Node<K,V>[] table;
...
...

@SuppressWarnings({"rawtypes","unchecked"})
Node<K,V>[] tab = (Node<K,V>[])new Node[cap];
table = tab;

// Read the keys and values, and put the mappings in the HashMap
for (int i = 0; i < mappings; i++) {
    @SuppressWarnings("unchecked")
    K key = (K) s.readObject();
    @SuppressWarnings("unchecked")
    V value = (V) s.readObject();
    putVal(hash(key), key, value, false, false);
}
```

readObject() 메소드에서 각종 경고 어노테이션과 함께 raw type으로 생성한 뒤 강제 형변환 하는 부분이 있습니다.
내부구현에 해당되고 저런 케이스가 발생하는 상황에 대해서 각종 방어코딩이 되어있을 것 같지만 일단 가능하기는 한것 같습니다.

그래서 책 예제에도 적용을 해보았는데요.
마찬가지로 책 예제에서도 raw type 생성 후 형변환으로 강제 제네릭 배열을 적용시키면 컴파일에러는 사라지지만 
잘못된 사용으로 런타임에서 에러를 만나게 되는 상황이 벌어지게 될것입니다.....

```java
List<String>[] stringLists = (List<String>[])new List[1];
List<Integer> intList = List.of(42);
Object[] objects = stringLists;
objects[0] = intList;
String s = stringLists[0].get(0);
System.out.println("s = " + s);
```
