### ISSUE TITLE
[item #38] 인터페이스로 확장된 Enum 예시에서

### ISSUE THREAD

**Issue by daeho-ro** [now-study/study-effective-java#53]
인터페이스로 확장된 Enum 예시에서 두 가지 방법으로 기존 Enum에 대한 test 메서드를 함께 사용할 수 있는 방법을 보여주고 있습니다.
그 중에서 두 번째 예시에서
```java
private static void test(Collection<? extends Operation> opSet,
                         double x, double y) {
    for (Operation op : opSet)
        System.out.printf("%f %s %f = %f%n",
                x, op, y, op.apply(x, y));
}
```
위와 같이 한정적 와일드 카드를 사용하는 경우에 좀 더 간단하고 메서드는 유연해졌지만, 특정 연산에서 EnumSet, EnumMap을 사용할 수 없다고 합니다.

이 말이 왜 나왔는지도 이해가 잘 안되고, 실제로 어떤 경우에 사용할 수 없다면 첫 번째 예시인 제네릭을 사용하는 경우에는 그것이 가능한지 궁금합니다.

**Comment by daeho-ro** [comment]
적어놓고 보니 인풋 타입이 Collection이라서 EnumSet도 받을 수 있을텐데, 확장된 이넘과 기존 이넘이 서로 다른 이넘이라서 특정 연산 조합을 만들 수 없다는 의미인 것 같기도 하고...

**Comment by hailey21** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/26457519/214582673-403a43cf-6915-41a1-8b65-2c509560413c.png">

BasicOperation과 ExtendedOperation은 둘다 Operation을 구현하고 있지만, 
사실상 둘은 서로 다른 열거타입이기 때문에 같은 열거 타입만 허용하는 EnumSet과 EnumMap은 둘을 동시에 담을 수 없어 한정적 와일드카드 타입으로 받은 객체에 대해 특정 연산을 사용할 수 없다고 서술한 것 같습니다. 
인터페이스로 제네릭을 지정해도 컴파일 에러가 납니다.

```java
public static void main(String[] args) {
        double x = Double.parseDouble(args[0]);
        double y = Double.parseDouble(args[1]);
        test(Arrays.asList(ExtendedOperation.values()), x, y);
        test(EnumSet.of(ExtendedOperation.EXP, BasicOperation.MINUS), x, y); // 컴파일 에러
    }
    private static void test(Collection<? extends Operation> opSet,
                             double x, double y) {
        for (Operation op : opSet)
            System.out.printf("%f %s %f = %f%n",
                    x, op, y, op.apply(x, y));
    }
```

첫 번째 예시인 제네릭 타입인 경우 `<T extends Enum<T> & Operation> Class<T>`, Class 객체가 열거 타입인 동시에 Operation의 하위 타입이어야 하고 Enum 타입을 명시해서 호출하고 있기 때문에.. 사실 어찌보면 구체적인 (단일)타입을 지정하고 있기 때문에 동일한 문제가 발생하지 않는다는 제가 생각할땐 약간 눈가리고 아웅식의 해석이 아닐까 싶습니다......
