### ISSUE TITLE
[item #02] 불변식(Invariant) 이 무엇인지 잘 모르겠어요

### ISSUE THREAD

**Issue by golch** [now-study/study-effective-java#6]
본문의 19페이지에 나옵니다.

**Comment by daeho-ro** [comment]
빌더를 생성하기 전에 개별 매개변수나 여러 매개변수에 대한 조건을 검사하여 유효성을 테스트할 수 있는데, 여러 매개변수에 걸쳐서 절대 변하지 않는 조건을 일종의 불변식이라고 표현하는 것 같습니다. 가장 간단한 불변식으로 시간에 대한 불변식을 아이템 50에서 소개하고 있습니다. 보통 end는 start 보다 항상 늦은 시간에 존재하므로, 시간에 대한 불변식은 다음과 같습니다.

```java
if (start.before(end)) {
    throw new Exception("시작은 종료보다 항상 앞서야 합니다.");
}
```

그래서 이러한 불변식을 가지는 클래스를 하나 만들어 보자면,

```java
public final class Period {

    private final Date start;
    private final Date end;

    public static class Builder {

        private final Date start;
        private final Date end;

        public Builder(Date start, Date end) {
            this.start = start;
            this.end = end;
        }

        public Period build() {
            if (this.start > this.end) {
                throw new Exception("종료가 시작보다 항상 크거나 같아야 합니다.")
            }
            return new Period(this);
        }
    }
}
```

이처럼 `build()` 안에서 불변식에 대한 유효성을 검증하는 과정을 거쳐서 빌드를 진행할 수 있을 겁니다. 물론 아이템 50에서 자세히 다루겠지만, 이러한 클래스에서 `Date` 타입은 가변이므로 외부에서 조작이 가능하고 이는 추후 다시 논의하는게 좋겠습니다.

**Comment by daeho-ro** [comment]
바로 다음 19페이지에서 설명이 나와있었군요!

> 한편, 불변식(invariant)은 프로그램이 실행되는 동안, 혹은 정해진 기간 동안 반드시 만족해야 하는 조건을 말한다. 다시 말해 변경을 허용할 수는 있으나 주어진 조건 내에서만 허용한다는 뜻이다. 예컨대 리스트의 크기는 반드시 0 이상이어야 하니, 만약 한순간이라도 음수 값이 된다면 불변식이 깨진 것이다.
