### ISSUE TITLE
[item #01] 정적 팩터리 메서드와 생성자 간 상관관계? 가 궁금합니다.

### ISSUE THREAD

**Issue by Heezzan** [now-study/study-effective-java#7]
단점 1. 상속을 하려면 public 이나 protected 생성자가 필요하니 정적 팩터리 메서드만 제공하면 하위 클래스를 만들 수 없다. (p.12) 라는 말이 정확이 이해가 안가서 예제를 확인하다 보니 제가 본 정적 팩터리 메서드의 예시들이 모두 private 인 기본 생성자를 가지더라고요.

정적 팩터리 메소드를 사용한다 -> 생성자를 통해 객체를 생성하지 않는다 -> 정적 팩터리 메소드를 사용해서 객체를 얻기 위해 어쨋든 객체를 생성하는 과정은 필요하니 private 생성자를 사용한다

이 생각의 흐름이 맞는건가요? 즉 정적 팩터리 메서드를 사용할 때 무조건 private 생성자를 사용하는건지, 아니면 자유이지만 위의 생각의 흐름에 따라 private 생성자를 사용하는 케이스가 많은건지 정적 팩터리 메서드와 생성자의 상관관계가 궁금합니다.

**Comment by hyojae93** [comment]
private 생성자를 무조건 사용해야만 하지는 않습니다.
"정적 팩터리 메서드만 제공하면" 이라는 뜻이
장점2와 관련이 되어있는데 정적 팩터리 메서드를 사용하는 이유중 인스턴스를 매번 생성하지 않고
하나로 통제하고 싶을때 priavte로 선언하여
클래스 내부에 인스턴스를 생성하고 컨트롤하여 외부에 정적 팩터리 메서드(만)를 제공하는 방식으로 사용했기 때문입니다.
