### ISSUE TITLE
[item #01] 인터페이스의 정적 메서드와 기본 메서드의 차이점은 무엇이고 기본메서드의 이점은 무엇일까요?

### ISSUE THREAD

**Issue by hailey21** [now-study/study-effective-java#8]
자바 8부터 정적 메서드를 가질 수 없다는 제한이 풀렸기 때문에 인스턴스화 불가 동반 클래스를 둘 이유가 별로 없다는 내용이 있습니다. 

인터페이스에서 많이 쓰고 있는 정적 메서드와 기본 메서드의 차이점이 무엇이고, 
제한이 풀려서 인터페이스가 정적 메서드를 가질 수 있게 되었을 때의 이점이 무엇일까요?

**Comment by hailey21** [comment]
어우 클릭잘못해서 이력이 너무 많이남았어요 죄송합니다;

**Comment by hyojae93** [comment]
인스턴스화 불가 동반 클래스는,
인스턴스를 만들 수 없는 프라이빗 생성자, 파이널 클래스로 상속을 막아야하니까 
하위클래스에서 상위클래스의 인스턴스를 만들 수 없었던 제약들을 자바 8부터 인스턴스 메서드를 제공함으로써
인터페이스를 만들어서 제공하는 기본 메서드를 만들건지
인터페이스를 직접 호출하는 정적 메서드를 만들건지 상황에 맞게 구성하여
인스턴스를 구현한 하위 클래스들의 인스턴스를 고치지 않고 
정적 팩토리 메서드들을 가진 클래스들을 많이 만들지 않아도 된다는 것과
반환 타입의 하위 객체를 반환 할수 있게 되었다는 것 
즉 유연성과 고정적이지 않은 타입을 설정 할 수 있어 이점을 얻을 수 있다고 설명하고 있습니다.
