### ISSUE TITLE
[item #05] 의존 객체 주입의 어지러운 예제 및 스프링을 통한 해소 예제

### ISSUE THREAD

**Issue by miyeon396** [now-study/study-effective-java#9]
30페이지 하단을 보면 

> 의존 객체 주입이 의존성이 수 천개나 되는 큰 프로젝트에서는 코드를 어지럽게 만들기도 한다.
> 대거, 주스, 스프링 같은 의존 객체 주입 프로젝트를 사용하면 이런 어지럼을 해소 할 수 있다

라고 이야기하는데, 어지럽게 만드는 예제와 스프링을 사용하여 어질러짐을 해소하는 간단한 케이스가 궁급합니다.

**Comment by hailey21** [comment]
어지럽게 만드는 예제는 일단 간단한 케이스를 만들기 어려울 듯 합니다..
그동안에 스프링의 편안함에 어마무시하게 길들여져서 굳이 궁금하시다면 기존에 구현된 소스를 직접 다시 순수 자바로 구현해보시는게 도움이 될것같아요 ㅠㅠ

간단한 예제를 첨부합니다.
실제로는 동작하는지 확인해보지 않은 개념적인 코드입니다.
```java
public class AppConfig {

    public MemberService memberService(){
        return new MemberServiceImpl(memberRepository());
    }

    private MemberRepository memberRepository() {
        return new MemoryMemberRepository();
    }

    public OrderService orderService(){
        return new OrderServiceImpl(memberRepository(), discountPolicy());
    }

    public DiscountPolicy discountPolicy(){
        return new RateDiscountPolicy();
    }
}
```

위와 같이 객체를 생성하고 연결해주는 역할을 해주는 클래스가 있을 때 
```java
public class OrderApp {

    public static void main(String[] args) {
        AppConfig appConfig = new AppConfig();

        MemberService memberService = appConfig.memberService();
        OrderService orderService = appConfig.orderService();

        Long memberId = 1L;
        Member member = new Member(memberId,"memberA", Grade.VIP);
        memberService.join(member);

        Order order = orderService.createOrder(memberId, "itemA", 20000);

        System.out.println("order = " + order);
        System.out.println(order.calculatePrice());
    }
}
```
이렇게 우리는 직접 주입할 객체를 만들고 연결 클래스를 호출해서 필요한 객체를 호출할 수 있습니다.

그러나 스프링 프레임워크를 사용하면 AppConfig와 같은 연결 클래스를 직접 생성하는 대신 각각의 구현체에 @Service 어노테이션을 달고 생성자 또는 필드 주입 방식을 통해(우리가 흔히 사용하는 @RequiredArgsConstructor @Autowired 등 어노테이션 사용) 쉽고 간결하게 사용할 수 있습니다.

현재 우리 코드들의 대부분에 들어있는 내용입니다.
